# Generated by Django 3.2.4 on 2021-06-04 19:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('obs', models.TextField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='04/06/21')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('implant_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Neodent Alvim CM', 'Neodent Alvim CM'), ('Neodent Drive CM', 'Neodent Drive CM'), ('SIN SWC CM', 'SIN SWC CM'), ('SIN Strong CM', 'SIN Strong CM')], max_length=50), size=None)),
                ('implant_size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('3.5x8', '3.5x8'), ('3.5x10', '3.5x10'), ('3.5x11.5', '3.5x11.5'), ('3.5x13', '3.5x13'), ('3.5x15', '3.5x15'), ('4.3x8', '4.3x8'), ('4.3x10', '4.3x10'), ('4.3x11.5', '4.3x11.5'), ('4.3x13', '4.3x13'), ('4.3x15', '4.3x15')], max_length=50), size=None)),
                ('area', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47)], max_length=50), size=None)),
                ('obs', models.TextField(blank=True, max_length=600)),
                ('stage', models.CharField(choices=[('Finalizado', 'Finalizado'), ('Espera', 'Espera'), ('Andamento', 'Andamento')], default='Espera', max_length=50)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ccip.client')),
                ('usuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('3.5x8', '3.5x8'), ('3.5x10', '3.5x10'), ('3.5x11.5', '3.5x11.5'), ('3.5x13', '3.5x13'), ('3.5x15', '3.5x15'), ('4.3x8', '4.3x8'), ('4.3x10', '4.3x10'), ('4.3x11.5', '4.3x11.5'), ('4.3x13', '4.3x13'), ('4.3x15', '4.3x15')], default='3.5x8', max_length=30)),
                ('type', models.CharField(choices=[('Neodent Alvim CM', 'Neodent Alvim CM'), ('Neodent Drive CM', 'Neodent Drive CM'), ('SIN SWC CM', 'SIN SWC CM'), ('SIN Strong CM', 'SIN Strong CM')], default='Neodent Alvim CM 3.5x8', max_length=60)),
                ('quantity', models.IntegerField(default=1)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
