# Generated by Django 3.2.4 on 2021-06-04 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Espera', 'Espera'), ('Andamento', 'Andamento'), ('Finalizado', 'Finalizado')], default='Espera', max_length=50),
        ),
    ]
