# Generated by Django 3.2.4 on 2021-06-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0002_alter_surgery_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgery',
            old_name='usuario',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Espera', 'Espera'), ('Finalizado', 'Finalizado'), ('Andamento', 'Andamento')], default='Espera', max_length=50),
        ),
    ]
