# Generated by Django 3.2.4 on 2021-06-05 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0004_alter_surgery_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(default='05/06/21'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('Espera', 'Espera'), ('Andamento', 'Andamento')], default='Espera', max_length=50),
        ),
    ]
