# Generated by Django 3.2.4 on 2021-06-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0005_auto_20210605_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(default='07/06/21'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('Andamento', 'Andamento'), ('Espera', 'Espera')], default='Espera', max_length=50),
        ),
    ]
