# Generated by Django 3.2.4 on 2021-06-20 22:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0006_auto_20210607_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(default='20/06/21'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='implant_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Neodent Alvim CM', 'Neodent Alvim CM'), ('Neodent Drive CM', 'Neodent Drive CM'), ('SIN SWC CM', 'SIN SWC CM'), ('SIN Strong CM', 'SIN Strong CM'), ('SIN Unitite CM', 'SIN Unitite CM')], max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('Espera', 'Espera'), ('Andamento', 'Andamento')], default='Espera', max_length=50),
        ),
    ]
