# Generated by Django 3.2.4 on 2021-06-28 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0008_alter_surgery_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=50),
        ),
        migrations.AddField(
            model_name='surgery',
            name='prot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='implant',
            name='size',
            field=models.CharField(choices=[('4x5', '4x5'), ('4x6', '4x6'), ('5x5', '5x5'), ('5x6', '5x6'), ('6x5', '6x5'), ('6x6', '6x6'), ('3.5x8', '3.5x8'), ('3.5x10', '3.5x10'), ('3.5x11.5', '3.5x11.5'), ('3.5x13', '3.5x13'), ('3.5x15', '3.5x15'), ('4.3x8', '4.3x8'), ('4.3x10', '4.3x10'), ('4.3x11.5', '4.3x11.5'), ('4.3x13', '4.3x13'), ('4.3x15', '4.3x15')], default='3.5x8', max_length=30),
        ),
        migrations.AlterField(
            model_name='implant',
            name='type',
            field=models.CharField(choices=[('Neodent Alvim CM', 'Neodent Alvim CM'), ('Neodent Drive CM', 'Neodent Drive CM'), ('Neodent Titamax WS CM', 'Neodent Titamax WS CM'), ('SIN SWC CM', 'SIN SWC CM'), ('SIN Strong CM', 'SIN Strong CM'), ('SIN Unitite CM', 'SIN Unitite CM')], default='Neodent Alvim CM 3.5x8', max_length=60),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(default='28/06/21'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='implant_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Neodent Alvim CM', 'Neodent Alvim CM'), ('Neodent Drive CM', 'Neodent Drive CM'), ('Neodent Titamax WS CM', 'Neodent Titamax WS CM'), ('SIN SWC CM', 'SIN SWC CM'), ('SIN Strong CM', 'SIN Strong CM'), ('SIN Unitite CM', 'SIN Unitite CM')], max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Andamento', 'Andamento'), ('Espera', 'Espera'), ('Finalizado', 'Finalizado')], default='Espera', max_length=50),
        ),
    ]
