# Generated by Django 3.2.4 on 2021-06-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0009_auto_20210628_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surgery',
            name='prot',
        ),
        migrations.AddField(
            model_name='surgery',
            name='pmu',
            field=models.CharField(choices=[('Unitária', 'Unitária'), ('Múltipla', 'Múltipla'), ('Protocolo', 'Protocolo')], default='Unitária', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Espera', 'Espera'), ('Finalizado', 'Finalizado'), ('Andamento', 'Andamento')], default='Espera', max_length=50),
        ),
    ]
