# Generated by Django 3.2.4 on 2021-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccip', '0011_auto_20210628_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implant',
            name='type',
            field=models.CharField(choices=[('Neodent Alvim CM', 'Neodent Alvim CM'), ('Neodent Drive CM', 'Neodent Drive CM'), ('Neodent Titamax WS CM', 'Neodent Titamax WS CM'), ('Nobel Replace CM', 'Nobel Replace CM'), ('SIN SWC CM', 'SIN SWC CM'), ('SIN Strong CM', 'SIN Strong CM'), ('SIN Unitite CM', 'SIN Unitite CM')], default='Neodent Alvim CM 3.5x8', max_length=60),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='date',
            field=models.DateField(default='07/07/21'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='pmu',
            field=models.CharField(choices=[('Múltipla', 'Múltipla'), ('Unitária', 'Unitária'), ('Protocolo', 'Protocolo')], default='Unitária', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='stage',
            field=models.CharField(choices=[('Espera', 'Espera'), ('Andamento', 'Andamento'), ('Finalizado', 'Finalizado')], default='Espera', max_length=50),
        ),
    ]
